### ISSUE TITLE
Invalid Syntax: Failed to load the extension on latest fresh install of Oobabooga and Extension

### ISSUE THREAD

**Issue by juicyroots** [Trojaner/text-generation-webui-stable_diffusion#10]
The extension won't load, even on a fresh install of everything. 

13:38:16-145297 ERROR Failed to load the extension "text-generation-webui-stable_diffusion".
Traceback (most recent call last):
  File "D:\LLMs\oob\modules\extensions.py", line 37, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1
    import extensions.text-generation-webui-stable_diffusion.script

SyntaxError: invalid syntax

**Comment by juicyroots** [comment]
Am I missing something?

**Comment by Trojaner** [comment]
Rename the extension directory to "stable_diffusion" and adjust the enabled extensions in settings.json/yaml accordingly.
Don't forget to pip install the dependencies, see the README for instructions for that.

**Comment by juicyroots** [comment]
Duh. I was being dumb. Apologies.
