### ISSUE TITLE
Issue: Lost context in Continous mode

### ISSUE THREAD

**Issue by TheInvisibleMage** [Trojaner/text-generation-webui-stable_diffusion#13]
## Description
Continuous mode seems non-functional about half of the time; no image is produced.
Debugging shows that the context seems to "lag behind" sometimes. An example debug sequence is below.

- First input sent. Context at line 54 of script.py is None. By line 158 of script.py, context is still none. Since we are not in interactive mode, the following check fails, so no image is ever generated.
- Second input sent. Context at line 54 of script.py shows information relating to the first input instead. By line 158 of script.py, context is None again.

It should be noted that the above is not consistent; sometimes the desired context makes it through, and the image generates successfully. This would suggest some kind of race condition around the context being set/loaded.

UI after one failure, during second attempt: 
![image](https://github.com/Trojaner/text-generation-webui-stable_diffusion/assets/64934262/b4bd4e7f-aab4-4728-83dc-94b5104408c3)

Debug during second attempt:
![image](https://github.com/Trojaner/text-generation-webui-stable_diffusion/assets/64934262/0afac1d5-a6bd-4ce1-b52b-7e890fc2fcaf)

## Additional Info

- Branch: main
- Commit: d4667f830e49ba061339470e790fcc47d8be588f
-  Model used: TheBloke_NeuralHermes-2.5-Mistral-7B-GGUF

**Comment by Trojaner** [comment]
I noticed this issue as well but did not find a good way to reproduce it in a reliable way. Probably related to a different thread handling that part. I already reworked the way how the context is stored and it will no longer use a local thread state (as text-generation-webui doesn't support multithreading anyway). Might rework it further and make it part of `state` instead but for now it seems to be working.

I will push the related changes later this weekend as part of a bigger update that also fixes some other stuff like some values (especially booleans and enums) not being updated correctly via the UI.
