### ISSUE TITLE
i'm new to add manualy extension and things like that, so sorry if my problem could sound stupid

### ISSUE THREAD

**Issue by Flaxmore** [Trojaner/text-generation-webui-stable_diffusion#15]
i followed the installation guide but i really don't get the last two step couse i can't find the file settings.json
![image](https://github.com/Trojaner/text-generation-webui-stable_diffusion/assets/110793030/23493984-e472-4731-8b57-712e104ccd4b)
(these are the two steps i can't get)

**Comment by Zalimar** [comment]
I'm blocked in the same way

**Comment by Trojaner** [comment]
Please check the text-generation-webui documentation on how to configure settings.json / settings.yaml
