### ISSUE TITLE
idk what is appening 

### ISSUE THREAD

**Issue by Flaxmore** [Trojaner/text-generation-webui-stable_diffusion#16]
![image](https://github.com/Trojaner/text-generation-webui-stable_diffusion/assets/110793030/d1d31c98-8ecd-4e2b-a23f-5ca4102bcc9d)

**Comment by atawfiq-it** [comment]
Hi
I had the same problem and the solution is very simple, just add `'--api'` at the end of `COMMANDLINE_ARGS` in the A111 `webui-user.bat` file.
`set COMMANDLINE_ARGS=--xformers --api`
