### ISSUE TITLE
Reloading the text model fails, saying Tokenizer in Transformers format was not found

### ISSUE THREAD

**Issue by phr00t** [Trojaner/text-generation-webui-stable_diffusion#17]
I'm using the VRAM option since my text model is very large. It seems an image gets created, but then it has trouble reloading the model:

![image](https://github.com/Trojaner/text-generation-webui-stable_diffusion/assets/5983470/940d92fd-2654-4ab7-a143-6e10a36cdb61)

text-generation-webui loads the model fine, but then it doesn't seem to be correctly reloading it after stable_diffusion unloads it to run the image generator.

It looks like it is trying to load "None" for some reason...?

**Comment by phr00t** [comment]
I fixed this in my fork: https://github.com/Trojaner/text-generation-webui-stable_diffusion/commit/ab6d2a15ef78bc9a87793481a5cf7db1a63a9982

**Comment by Trojaner** [comment]
I checked out your fork, can you do a PR once your changes are finalized?

Thanks!

**Comment by phr00t** [comment]
I didn't do a great job of isolating just these changes, as I made some other improvements on my fork. It might be easier to just cherry pick these two commits to fix this bug:

https://github.com/Trojaner/text-generation-webui-stable_diffusion/commit/ab6d2a15ef78bc9a87793481a5cf7db1a63a9982

https://github.com/Trojaner/text-generation-webui-stable_diffusion/commit/fb2a9aac52f2492540ecefdf813dd2df12661408

**Comment by Trojaner** [comment]
Its merged now, thanks 👍
