### ISSUE TITLE
where to put settings.json

### ISSUE THREAD

**Issue by GGuussss** [Trojaner/text-generation-webui-stable_diffusion#4]
hi

I m using oobabooga on windows

I'm trying to setting up text-generation-webui-stable_diffusion extension, but where can I put setting.json ? 
it seems to do nothing inside the extension folder or at the root of oobabooga.

**Comment by Trojaner** [comment]
It needs to be in root folder of oobabooga. You may have to add "--settings settings.json" to command line parameters
