### ISSUE TITLE
The Trigger Prompt Doesn't Seem to Impact the Model?

### ISSUE THREAD

**Issue by juicyroots** [Trojaner/text-generation-webui-stable_diffusion#6]
This config setting in settings.yaml does not seem to change how the model responds:

## The prompt to trigger a description of the subject.
stable_diffusion-interactive_mode_description_prompt: >
You are now a text generator for the Stable Diffusion AI image generator. You will generate a text prompt for it.
Describe [subject] using comma-separated tags only. Do not use sentences.
...

Is there something that I need to do, or a particular model that I need to use? What's the trick? Thank you!

**Comment by Trojaner** [comment]
This option only works in trigger mode

**Comment by juicyroots** [comment]
Thanks for the response! Appreciate it. I see a few options under 'Trigger Mode'

![Text generation web UI - Brave-000101](https://github.com/Trojaner/text-generation-webui-stable_diffusion/assets/1800017/8059d3c3-346d-4bf3-bd8f-f0ca64b1a336)

Manual, Interactive, Continuous... Does only one of those work?

**Comment by Trojaner** [comment]
- Manual trigger mode is currently not implemented. The other two should work. Manual will allow you to trigger an image generation by pressing a related button before sending your text.
- Continuous trigger mode will always generate an image but currently ignore context, hence it will always only use default prompt + base prompt. Chat context based image generation for it is [still todo](https://github.com/Trojaner/text-generation-webui-stable_diffusion/blob/main/script.py#L69).
- Interactive trigger mode will only generate an image when an input matches the [configured regex](https://github.com/Trojaner/text-generation-webui-stable_diffusion/blob/main/settings.debug.yaml#L61). The default regex will trigger if the sentence starts with e.g. "send me a picture of [subject]". This mode is chat context aware and will use the prompt template you mentioned in the first post.

> This option only works in trigger mode  

Sorry, I forgot to specify that it's for the interactive trigger mode

Keep in mind that the extension UI is currently experimental and settings should be set in the related settings json or yaml file instead. This will also make them persistent.

**Comment by Trojaner** [comment]
Closing as resolved. Feel free to open a new issue if the issue persists.

Also prompt generation modes have been added for interactive and continuous modes in v1.1:

```yaml
## Set's how the base prompt for image generation should be generated. Possible values:
##  - "default_prompt": Uses the default_prompt option as a static prompt ignoring any chat context.
##  - "generated_text": Uses the generated output as-is as prompt.
##  - "dynamic": Uses a dynamic prompt using the subject_regex, default_subject and description_prompt options.
## The result is combined with the base_prompt_suffix and base_negative_prompt options.
stable_diffusion-interactive_mode_prompt_generation_mode: "dynamic"
```

```yaml
## Set's how the base prompt for image generation should be generated. Possible values:
##  - "default_prompt": Uses the default_prompt option as a static prompt ignoring any chat context.
##  - "generated_text": Uses the generated output as-is as prompt.
## The result is combined with the base_prompt_suffix and base_negative_prompt options.
stable_diffusion-continuous_mode_prompt_generation_mode: "generated_text"
```

**Comment by sandrejev** [comment]
It doesn' work for me either. The error is in script.py
```
        text = (
            description_prompt
            if ext_params.interactive_mode_prompt_generation_mode
            == InteractiveModePromptGenerationMode.DYNAMIC
            else text
        )
```
should be replaced with
```
        prompt = (
            description_prompt
            if ext_params.interactive_mode_prompt_generation_mode
            == InteractiveModePromptGenerationMode.DYNAMIC
            else text
        )
```
