### ISSUE TITLE
Failed to load the extension "text-generation-webui-stable_diffusion".

### ISSUE THREAD

**Issue by CRCODE22** [Trojaner/text-generation-webui-stable_diffusion#7]
2023-12-15 08:53:44 ERROR:Failed to load the extension "text-generation-webui-stable_diffusion".
Traceback (most recent call last):
  File "K:\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1
    import extensions.text-generation-webui-stable_diffusion.script
                          ^
SyntaxError: invalid syntax

**Comment by Trojaner** [comment]
Make sure the extension folder is named "stable_diffusion"

**Comment by CRCODE22** [comment]
> Make sure the extension folder is named "stable_diffusion"

Ok I will try that I copied and pasted the link from the github into text generation webui and it cloned it in text-generation-webui-stable_diffusion I will rename it to stable_diffusion.

**Comment by Trojaner** [comment]
Closing as completed. The readme has been updated with better installation instructions. Let me know if the issue persists.
