### ISSUE TITLE
error using reactor face model

### ISSUE THREAD

**Issue by JetsonFlyers** [Trojaner/text-generation-webui-stable_diffusion#8]
I am getting the following error when attempting to use a Reactor facemodel checkpoint as the source for a faceswap.

2023-12-24 12:45:49 ERROR:[SD WebUI Integration] Reactor failed to swap faces: (500, '{"error":"HTTPException","detail":"Invalid encoded image","body":"","errors":""}')

An image source is working fine. I have attempted moving the checkpoint to the extensions/stable_diffusion/assets dir and also pointing to it in the ..\stable-diffusion-webui\models\reactor\faces directory both with same results.

Entry into Source face field: "checkpoint:///extensions/stable_diffusion/assets/name.safetensors", "checkpoint://name.safetensors" - also tried "file://...."

**Comment by Trojaner** [comment]
`checkpoint:///` should only contain the file name of the checkpoint without the `.safetensors` part, it's not a file path. For example, if your checkpoint is called name.safetensors it should be set to `checkpoint:///name` . The checkpoint file itself needs to be located inside the `\models\reactor\faces` folder in `stable-diffusion-webui` and not in `text-generation-webui`. 

On the contrary, `file:///` refers to image files relative to the `text-generation-webui` directory instead.

Let me know if you have any questions or the issue persists.
